const image = id => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=82`;
const meals = [
  ['โบวล์แซลมอนมิโสะ','high-protein energy','โปรตีนสูง',528,38,46,22,'แซลมอนอบ ผักมิโสะ ข้าวกล้อง อะโวคาโด และงา','โอเมกา-3 จากแซลมอนช่วยดูแลหัวใจและสมอง','photo-1547592180-85f173990554'],
  ['โบวล์โกลเด้นโกลว์','plant-powered energy','พลังจากพืช',472,19,62,18,'ถั่วชิกพีขมิ้น มันหวาน เคล และทาฮินีเลมอน','ผักหลากสีให้ใยอาหารและสารต้านอนุมูลอิสระ','photo-1512621776951-a57141f2eefd'],
  ['จานไก่สมุนไพร','high-protein','โปรตีนสูง',510,42,39,21,'ไก่ย่าง ฟรีเคห์ แตงกวา สมุนไพร และซอสเขียว','โปรตีนไขมันต่ำช่วยเสริมสร้างและซ่อมแซมกล้ามเนื้อ','photo-1532550907401-a500c9a57435'],
  ['สลัดกรีนก็อดเดส','plant-powered','พลังจากพืช',396,16,35,23,'ผักกรอบ เอดามาเมะ อะโวคาโด แอปเปิล และเมล็ดฟักทอง','ไขมันดีช่วยให้ร่างกายดูดซึมวิตามินจากพืช','photo-1498837167922-ddd27525d352'],
  ['โบวล์เลนทิลเครื่องเทศ','plant-powered high-protein','พลังจากพืช',448,24,59,13,'เลนทิลอุ่น บรอกโคลีย่าง แครอต และโยเกิร์ตยี่หร่า','เลนทิลมีใยอาหารและธาตุเหล็ก ช่วยให้พลังงานสม่ำเสมอ','photo-1515003197210-e0cd71810b5f'],
  ['โอ๊ตโปรตีนเบอร์รี','high-protein energy','พลังงานและโฟกัส',414,29,51,12,'โอ๊ตครีมมี่ กรีกโยเกิร์ต เบอร์รี อัลมอนด์ และเจีย','โปรตีนและโอ๊ตช่วยให้รู้สึกอิ่มและมีพลังงานนานขึ้น','photo-1517673400267-0251440c45dc'],
  ['พาสต้าเพสโต้ไก่','high-protein energy','โปรตีนสูง',546,36,55,20,'พาสต้าโฮลวีต ไก่ย่าง เพสโต้โหระพา และมะเขือเทศ','คาร์บเชิงซ้อนและโปรตีนช่วยเติมพลังหลังวันยาวนาน','photo-1473093295043-cdd812d0e601'],
  ['เต้าหู้เทอริยากิ','plant-powered high-protein','พลังจากพืช',438,25,52,15,'เต้าหู้ย่าง ข้าวกล้อง บรอกโคลี และซอสเทอริยากิ','โปรตีนจากถั่วเหลืองเป็นทางเลือกจากพืชที่อิ่มนาน','photo-1546069901-ba9599a7e63c'],
  ['สลัดทูน่าถั่วขาว','high-protein','โปรตีนสูง',422,33,31,19,'ทูน่า ถั่วขาว ผักร็อกเก็ต มะเขือเทศ และมะกอก','ทูน่าและถั่วให้โปรตีน พร้อมไฟเบอร์ที่เป็นมิตรต่อลำไส้','photo-1512621776951-a57141f2eefd'],
  ['ข้าวผัดคีนัวผัก','plant-powered energy','พลังงานและโฟกัส',462,18,65,14,'คีนัว ผักหลากสี ถั่วลันเตา และเม็ดมะม่วงหิมพานต์','คีนัวมีแมกนีเซียมและใยอาหารเพื่อพลังงานที่มั่นคง','photo-1490645935967-10de6ba17061'],
  ['เบอร์ริโตโบวล์เนื้อไม่ติดมัน','high-protein energy','โปรตีนสูง',566,41,58,19,'เนื้อไม่ติดมัน ข้าวโพด ถั่วดำ ข้าว และซัลซ่าสด','ธาตุเหล็กและโปรตีนช่วยสนับสนุนพลังงานของร่างกาย','photo-1543339308-43e59d6b73a6'],
  ['แกงเขียวหวานผัก','plant-powered','พลังจากพืช',401,14,48,18,'ผักตามฤดูกาล เต้าหู้ ข้าวหอมมะลิ และกะทิพอดีคำ','ผักหลากชนิดช่วยให้ได้รับวิตามินและแร่ธาตุหลายรูปแบบ','photo-1455619452474-d2be8b1e70cd'],
  ['โบวล์กุ้งมะนาว','high-protein','โปรตีนสูง',455,35,49,14,'กุ้งย่าง ข้าวกล้อง กะหล่ำม่วง และอะโวคาโด','กุ้งเป็นโปรตีนคุณภาพดีพร้อมซีลีเนียม','photo-1504674900247-0877df9cc836'],
  ['โทสต์อะโวคาโดไข่','energy','พลังงานและโฟกัส',387,17,38,20,'ขนมปังโฮลเกรน อะโวคาโด ไข่ต้ม และไมโครกรีน','ไขมันไม่อิ่มตัวและไข่ช่วยให้มื้อเช้าสมดุล','photo-1541519227354-08fa5d50c44d'],
  ['ซุปฟักทองเมล็ดเจีย','plant-powered','พลังจากพืช',342,13,47,12,'ฟักทองอบ ถั่วเลนทิลแดง เมล็ดเจีย และขนมปังธัญพืช','เบต้าแคโรทีนจากฟักทองช่วยสนับสนุนสุขภาพโดยรวม','photo-1547592166-23ac45744acd'],
  ['โยเกิร์ตกรีกทรอปิคอล','high-protein energy','พลังงานและโฟกัส',368,27,43,10,'กรีกโยเกิร์ต มะม่วง กล้วย กราโนลา และเมล็ดแฟลกซ์','โปรตีนและจุลินทรีย์ที่มีประโยชน์ช่วยเริ่มวันอย่างสดใส','photo-1488477181946-6428a0291777']
].map(([name,category,tag,calories,protein,carbs,fats,description,benefit,img])=>({name,category,tag,calories,protein,carbs,fats,description,benefit,image:image(img)}));
const grid=document.querySelector('#menu-grid'),dialog=document.querySelector('#nutrition-dialog'),dialogContent=document.querySelector('#dialog-content'),proteinGoal=75;let today=JSON.parse(localStorage.getItem('nouri-today')||'[]');
function renderTracker(){const t=today.reduce((s,m)=>({calories:s.calories+m.calories,protein:s.protein+m.protein,carbs:s.carbs+m.carbs,fats:s.fats+m.fats}),{calories:0,protein:0,carbs:0,fats:0}),p=Math.min(100,Math.round(t.protein/proteinGoal*100));document.querySelector('#protein-total').textContent=`${t.protein}g`;document.querySelector('#protein-percent').textContent=`${p}%`;document.querySelector('.protein-ring').style.background=`conic-gradient(var(--green) ${p*3.6}deg,#d9e4d2 0deg)`;document.querySelector('#calorie-total').textContent=`${t.calories} kcal`;document.querySelector('#carb-total').textContent=`${t.carbs}g`;document.querySelector('#fat-total').textContent=`${t.fats}g`;document.querySelector('#calorie-bar').style.width=`${Math.min(100,t.calories/20)}%`;document.querySelector('#carb-bar').style.width=`${Math.min(100,t.carbs/2.5)}%`;document.querySelector('#fat-bar').style.width=`${Math.min(100,t.fats/.7)}%`;document.querySelector('#tracker-message').textContent=today.length?`เพิ่มแล้ว ${today.length} มื้อ · ${t.protein>=proteinGoal?'ถึงเป้าโปรตีนวันนี้แล้ว':`อีก ${proteinGoal-t.protein}g ถึงเป้าโปรตีนวันนี้`}`:'เริ่มบันทึกมื้อแรกที่ดีต่อร่างกายของคุณได้เลย'}
function renderMeals(filter='all'){grid.innerHTML=meals.filter(m=>filter==='all'||m.category.includes(filter)).map(m=>`<article class="meal-card"><div class="meal-image"><img src="${m.image}" alt="${m.name}" loading="lazy"><span class="meal-type">${m.tag}</span></div><div class="meal-content"><div class="meal-title-row"><h3>${m.name}</h3><span class="calories">${m.calories} kcal</span></div><p class="meal-description">${m.description}</p><div class="protein-row"><span class="protein">โปรตีน ${m.protein}g</span><button class="details" data-meal="${meals.indexOf(m)}">โภชนาการ <span>→</span></button></div></div></article>`).join('')}
function updateBmi(weight,height){const bmi=weight/((height/100)**2),label=bmi<18.5?'ต่ำกว่าเกณฑ์น้ำหนักปกติสำหรับผู้ใหญ่':bmi<25?'อยู่ในเกณฑ์น้ำหนักปกติสำหรับผู้ใหญ่':bmi<30?'สูงกว่าเกณฑ์น้ำหนักปกติสำหรับผู้ใหญ่':'อยู่ในเกณฑ์โรคอ้วนสำหรับผู้ใหญ่';document.querySelector('#bmi-result').textContent=bmi.toFixed(1);document.querySelector('#bmi-note').textContent=`${label} · BMI เป็นเพียงเครื่องมือคัดกรอง ไม่ใช่การวินิจฉัย`}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');renderMeals(b.dataset.filter)}));grid.addEventListener('click',e=>{const b=e.target.closest('[data-meal]');if(!b)return;const m=meals[b.dataset.meal];dialogContent.innerHTML=`<p class="eyebrow"><span></span>${m.tag}</p><h2>${m.name}</h2><p>${m.description}</p><div class="nutrition-stats"><div><b>${m.protein}g</b><small>โปรตีน</small></div><div><b>${m.carbs}g</b><small>คาร์บ</small></div><div><b>${m.fats}g</b><small>ไขมันดี</small></div></div><p><strong>${m.calories} แคลอรี</strong> ต่อหนึ่งหน่วยบริโภค</p><div class="benefit-callout"><strong>ทำไมร่างกายคุณชอบมื้อนี้</strong><p>${m.benefit}</p></div><button class="add-meal" data-add="${b.dataset.meal}">เพิ่มในวันนี้ +</button>`;dialog.showModal()});document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialogContent.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(!b)return;today.push(meals[b.dataset.add]);localStorage.setItem('nouri-today',JSON.stringify(today));renderTracker();dialog.close();document.querySelector('#tracker').scrollIntoView()});document.querySelector('#reset-day').addEventListener('click',()=>{today=[];localStorage.removeItem('nouri-today');renderTracker()});document.querySelector('#bmi-form').addEventListener('submit',e=>{e.preventDefault();const h=Number(document.querySelector('#height-input').value),w=Number(document.querySelector('#weight-input').value);if(!h||!w)return;localStorage.setItem('nouri-bmi',JSON.stringify({height:h,weight:w}));updateBmi(w,h)});document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll).scrollIntoView()));renderMeals();renderTracker();const savedBmi=JSON.parse(localStorage.getItem('nouri-bmi')||'null');if(savedBmi){document.querySelector('#height-input').value=savedBmi.height;document.querySelector('#weight-input').value=savedBmi.weight;updateBmi(savedBmi.weight,savedBmi.height)}
