export const catalogEmojiById = {
  "ground-pork": "🐖",
  "pork-belly": "🥓",
  "pork-loin": "🐖",
  "pork-liver": "🐖",
  "chicken-breast": "🐔",
  "chicken-drumstick": "🍗",
  "chicken-wing": "🍗",
  beef: "🥩",
  duck: "🦆",
  squid: "🦑",
  salmon: "🐟",
  "canned-tuna": "🐟",
  "blue-crab": "🦀",
  "chicken-egg": "🥚",
  "duck-egg": "🥚",
  "whole-milk": "🥛",
  "soy-milk": "🫘",
  "plain-yogurt": "🥣",
  "cheddar-cheese": "🧀",
  "steamed-white-rice": "🍚",
  "steamed-sticky-rice": "🍙",
  "cooked-brown-rice": "🍚",
  "glass-noodles": "🍜",
  "yellow-egg-noodles": "🍜",
  "white-bread": "🍞",
  "rolled-oats": "🌾",
  "sweet-potato": "🍠",
  potato: "🥔",
  "white-tofu": "🫘",
  "fried-tofu": "🫘",
  "roasted-peanuts": "🥜",
  "mung-beans": "🫘",
  cashews: "🥜",
  "napa-cabbage": "🥬",
  lettuce: "🥬",
  "bok-choy": "🥬",
  cabbage: "🥬",
  broccoli: "🥦",
  carrot: "🥕",
  cucumber: "🥒",
  tomato: "🍅",
  onion: "🧅",
  shallot: "🧅",
  garlic: "🧄",
  lemongrass: "🌿",
  "mung-bean-sprouts": "🌱",
  pumpkin: "🎃",
  "straw-mushroom": "🍄",
  "oyster-mushroom": "🍄",
  coriander: "🌿",
  scallion: "🌿",
  "ripe-mango": "🥭",
  "ripe-papaya": "🍈",
  pineapple: "🍍",
  watermelon: "🍉",
  "mandarin-orange": "🍊",
  guava: "🍐",
  longan: "🍇",
  "coconut-water": "🥥",
  "fish-sauce": "🐟",
  "light-soy-sauce": "🧂",
  "oyster-sauce": "🦪",
  "granulated-sugar": "🧂",
  "soybean-oil": "🫒",
  "coconut-milk": "🥥",
  "chicken-broth": "🍲",
  "yellow-curry-powder": "🍛",
  "rice-flour": "🌾",
  "wheat-flour": "🌾",
  ketchup: "🍅",
  "table-salt": "🧂",
  "black-pepper": "🌶️",
  "fresh-ginger": "🫚",
  "smoked-ham": "🥓",
  "sweetened-condensed-milk": "🥛",
  "roast-duck": "🦆",
  "pork-fried-rice": "🐖🍚",
  "crab-fried-rice": "🦀🍚",
  "american-fried-rice": "🍳🍚",
  "garlic-pepper-pork": "🐖🧄",
  "ginger-chicken": "🐔🫚",
  "bok-choy-tofu": "🥬🫘",
  "bean-sprout-tofu": "🌱🫘",
  "pork-omelet": "🍳🐖",
  "steamed-egg": "🥚",
  "garlic-fried-pork-rice": "🐖🧄",
  "crispy-pork-rice": "🐖🍚",
  "chicken-rice": "🐔🍚",
  "chicken-biryani-rice": "🐔🍛",
  "roast-duck-rice": "🦆🍚",
  "grilled-chicken-sticky-rice": "🐔🍙",
  "mango-sticky-rice": "🥭🍚",
  "rice-with-omelet": "🍳🍚",
  "fried-chicken-rice": "🍗🍚",
  "chicken-curry-rice": "🐔🍛",
  "glass-noodle-clear-soup": "🍜",
  "chicken-curry": "🐔🍛",
  "hat-yai-fried-chicken": "🍗",
  "grilled-chicken": "🐔",
  "grilled-pork-skewers": "🐖🍢",
  "fish-sauce-fried-wings": "🍗",
};

const ingredientRules = [
  [["กุนเชียง", "หมูยอ", "แหนม", "หมู", "pork", "ham"], "🐖"],
  [["ไก่", "chicken"], "🐔"],
  [["เป็ด", "duck"], "🦆"],
  [["วัว", "beef"], "🥩"],
  [["กุ้ง", "shrimp"], "🦐"],
  [["ปู", "crab"], "🦀"],
  [["ปลาหมึก", "squid"], "🦑"],
  [["ปลา", "fish", "tuna", "salmon"], "🐟"],
  [["หอย", "oyster", "mussel", "clam"], "🦪"],
  [["ไข่", "egg"], "🥚"],
  [["นม", "milk"], "🥛"],
  [["ชีส", "cheese"], "🧀"],
  [["โยเกิร์ต", "yogurt"], "🥣"],
  [["ข้าว", "rice"], "🍚"],
  [["เส้น", "noodle"], "🍜"],
  [["ขนมปัง", "bread"], "🍞"],
  [["แป้ง", "flour"], "🌾"],
  [["มันเทศ", "sweet potato"], "🍠"],
  [["มันฝรั่ง", "potato"], "🥔"],
  [["ถั่ว", "bean", "nut", "peanut", "cashew"], "🫘"],
  [["เต้าหู้", "tofu"], "🫘"],
  [["กะหล่ำ", "ผักกาด", "กวางตุ้ง", "lettuce", "cabbage"], "🥬"],
  [["บรอกโคลี", "broccoli"], "🥦"],
  [["แครอท", "carrot"], "🥕"],
  [["แตงกวา", "cucumber"], "🥒"],
  [["มะเขือเทศ", "tomato"], "🍅"],
  [["ต้นหอม", "scallion", "spring onion"], "🌿"],
  [["หอม", "onion", "shallot"], "🧅"],
  [["กระเทียม", "garlic"], "🧄"],
  [["ถั่วงอก", "sprout"], "🌱"],
  [["ฟักทอง", "pumpkin"], "🎃"],
  [["เห็ด", "mushroom"], "🍄"],
  [["ผักชี", "โหระพา", "กะเพรา", "ต้นหอม", "herb", "basil", "coriander"], "🌿"],
  [["มะม่วง", "mango"], "🥭"],
  [["มะละกอ", "papaya"], "🍈"],
  [["สับปะรด", "pineapple"], "🍍"],
  [["แตงโม", "watermelon"], "🍉"],
  [["ส้ม", "orange"], "🍊"],
  [["ฝรั่ง", "guava"], "🍐"],
  [["ลำไย", "longan"], "🍇"],
  [["มะพร้าว", "coconut"], "🥥"],
  [["มะนาว", "lime", "lemon"], "🍋"],
  [["น้ำปลา", "fish sauce"], "🐟"],
  [["เกลือ", "น้ำตาล", "ซีอิ๊ว", "ซอส", "salt", "sugar", "sauce"], "🧂"],
  [["น้ำมัน", "oil"], "🫒"],
  [["ขิง", "ginger"], "🫚"],
  [["พริก", "pepper", "chili"], "🌶️"],
];

const recipeRules = [
  [["มะม่วง", "mango"], "🥭🍚"],
  [["ต้มยำ", "tom yum"], "🦐🍲"],
  [["ยำทะเล", "ยำวุ้นเส้น", "seafood salad"], "🦐🥗"],
  [["ผัดไทย", "pad thai"], "🦐🍜"],
  [["ซีอิ๊ว", "see ew"], "🍜"],
  [["ราดหน้า", "rad na"], "🍜"],
  [["ก๋วยเตี๋ยว", "บะหมี่", "ขนมจีน", "ข้าวซอย", "noodle soup"], "🍜"],
  [["ส้มตำ", "papaya salad"], "🥗🌶️"],
  [["ลาบ", "น้ำตก", "ยำ", "salad"], "🥗"],
  [["ปู", "crab"], "🦀🍚"],
  [["ปลา", "fish"], "🐟🍲"],
  [["ทะเล", "กุ้ง", "ปลาหมึก", "seafood", "shrimp", "squid"], "🦐🍲"],
  [["หอย", "mussel", "clam", "oyster"], "🦪🍲"],
  [["เป็ด", "duck"], "🦆🍚"],
  [["หมู", "pork"], "🐖🍚"],
  [["ไก่", "chicken"], "🐔🍚"],
  [["แกง", "curry"], "🍛"],
  [["ต้ม", "soup"], "🍲"],
  [["ไข่", "egg", "omelet"], "🍳🍚"],
  [["ทอด", "fried"], "🍳"],
  [["ย่าง", "grilled"], "🍢"],
  [["วุ้นเส้น", "noodle"], "🍜"],
  [["กวางตุ้ง", "bok choy"], "🥬🫘"],
  [["ถั่วงอก", "bean sprout"], "🌱🫘"],
  [["ข้าว", "rice"], "🍚"],
];

const matches = (text, terms) => terms.some(term => text.includes(term));

export function catalogEmoji(item, kind = "ingredients") {
  if (item?.id && catalogEmojiById[item.id]) return catalogEmojiById[item.id];
  const text = `${item?.nameTh || ""} ${item?.nameEn || ""} ${item?.category || ""} ${item?.id || ""}`.toLocaleLowerCase();
  const rules = kind === "recipes" ? recipeRules : ingredientRules;
  const match = rules.find(([terms]) => matches(text, terms));
  if (match) return match[1];
  return kind === "recipes" ? "🍽️" : "🥗";
}

export function CatalogEmoji({ item, kind = "ingredients", className = "", label }) {
  const description = label || `${kind === "recipes" ? "เมนู" : "วัตถุดิบ"} ${item?.nameTh || ""}`.trim();
  return <span role="img" aria-label={description} className={`catalog-emoji-art ${className}`.trim()}>{catalogEmoji(item, kind)}</span>;
}
